name: On Release, deploying to Prod

on:
  release:
    types: [published]

jobs:
  run-build-and-deploy:
    uses: ./.github/workflows/common-py3-mongodb-build-deploy.yml
    with:
      process_env: Prod
    secrets: inherit

  build-push-docker-image:
    uses: octopusden/octopus-base/.github/workflows/common-docker-build-deploy.yml@main
    with:
      tags: |
        ghcr.io/${{ github.repository }}:${{ github.ref_name }}
        ghcr.io/${{ github.repository }}:latest

